name: de_mad
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  game_levels_scrolling_map: ^0.0.7
  open_street_map_search_and_pick: ^0.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/drawable/map_vertical.png
    - assets/svg/map_vertical.svg
    - assets/drawable/map_vertical_point.png
    - assets/bgimage.jpg
    - assets/card1.jpg
    - assets/card2.jpg
    - assets/card3.jpg